FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

# Update and install necessary tools and Python
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y software-properties-common python3 python3-pip python-is-python3 git && \
    add-apt-repository universe

# Set environment variables
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Install Python libraries
RUN python3 -m pip install --upgrade pip
RUN pip install scikit-learn \
    git+https://github.com/huggingface/transformers.git \
    pillow==11.0.0 \
    torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 \
    scipy==1.14.1

# Prepare the workspace
RUN mkdir -p /data/programs/
COPY local_test.py /data/programs/test.py

# Set the entrypoint
ENTRYPOINT ["python3", "/data/programs/test.py"]