FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04
RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe
RUN apt-get -y update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN pip install scikit-learn

RUN pip install -q git+https://github.com/huggingface/transformers.git

RUN pip install pillow

RUN pip3 install torch torchvision torchaudio

RUN pip install scipy

COPY local_test.py /data/programs/test.py

ENTRYPOINT python3 /data/programs/test.py